/**
 * Generated from https://fonts.google.com/metadata/fonts by scripts/sync-google-fonts.mjs.
 * Each entry is "Family|category|weightMask", ordered by Google's popularity
 * ranking. The mask covers 400, 500, 600, 700 as bits 1, 2, 4, 8.
 */
export const GOOGLE_FONT_WEIGHTS = [400, 500, 600, 700] as const;

export type GoogleFontCategory = "s" | "r" | "d" | "h" | "m";

export const GOOGLE_FONT_INDEX: string[] = [
  "Roboto|s|15",
  "Open Sans|s|15",
  "Google Sans|s|15",
  "Lato|s|9",
  "Inter|s|15",
  "Montserrat|s|15",
  "Roboto Condensed|s|15",
  "Poppins|s|15",
  "Roboto Mono|m|15",
  "Noto Sans JP|s|15",
  "Oswald|s|15",
  "Noto Sans|s|15",
  "DM Sans|s|15",
  "Raleway|s|15",
  "Playfair Display|r|15",
  "Arimo|s|15",
  "Rubik|s|15",
  "Ubuntu|s|11",
  "Manrope|s|15",
  "Outfit|s|15",
  "Kanit|s|15",
  "Merriweather|r|15",
  "Archivo Black|s|1",
  "Noto Sans KR|s|15",
  "Nunito|s|15",
  "Work Sans|s|15",
  "Figtree|s|15",
  "Noto Sans TC|s|15",
  "Nunito Sans|s|15",
  "Source Sans 3|s|15",
  "JetBrains Mono|m|15",
  "Roboto Slab|r|15",
  "Prompt|s|15",
  "IBM Plex Sans|s|15",
  "Inconsolata|m|15",
  "Saira|s|15",
  "Karla|s|15",
  "Share Tech|s|1",
  "Smooch Sans|s|15",
  "Titillium Web|s|13",
  "Heebo|s|15",
  "Lora|r|15",
  "Plus Jakarta Sans|s|15",
  "Cormorant Garamond|r|15",
  "Quicksand|s|15",
  "Noto Sans SC|s|15",
  "PT Sans|s|9",
  "Libre Franklin|s|15",
  "Google Sans Flex|s|15",
  "Barlow Condensed|s|15",
  "Bebas Neue|s|1",
  "Fjalla One|s|1",
  "Mulish|s|15",
  "Dancing Script|h|15",
  "Anton|s|1",
  "Barlow|s|15",
  "Archivo|s|15",
  "EB Garamond|r|15",
  "Lobster Two|d|9",
  "Bricolage Grotesque|s|15",
  "Public Sans|s|15",
  "Inter Tight|s|15",
  "Instrument Serif|r|1",
  "Fraunces|r|15",
  "Cairo|s|15",
  "Jost|s|15",
  "Lexend|s|15",
  "Bitter|r|15",
  "Assistant|s|15",
  "Black Ops One|d|1",
  "Changa One|d|1",
  "Fira Sans|s|15",
  "Schibsted Grotesk|s|15",
  "Nanum Gothic|s|9",
  "Noto Serif|r|15",
  "Roboto Flex|s|15",
  "Space Grotesk|s|15",
  "Urbanist|s|15",
  "Alfa Slab One|d|1",
  "DM Serif Display|r|1",
  "Libre Baskerville|r|15",
  "Hind Siliguri|s|15",
  "PT Serif|r|9",
  "Overpass|s|15",
  "Rajdhani|s|15",
  "Instrument Sans|s|15",
  "Lilita One|d|1",
  "Source Code Pro|m|15",
  "Fredoka|s|15",
  "Exo 2|s|15",
  "Orbitron|s|15",
  "Source Serif 4|r|15",
  "Noto Sans Telugu|s|15",
  "Merriweather Sans|s|15",
  "Oxygen|s|9",
  "Crimson Text|r|13",
  "Newsreader|r|15",
  "IBM Plex Mono|m|15",
  "Pacifico|h|1",
  "Anek Telugu|s|15",
  "Josefin Sans|s|15",
  "Bungee|d|1",
  "Barlow Semi Condensed|s|15",
  "Noto Serif JP|r|15",
  "Tajawal|s|11",
  "Cinzel|r|15",
  "Slabo 27px|r|1",
  "PT Sans Narrow|s|9",
  "Sora|s|15",
  "Arvo|r|9",
  "Comfortaa|d|15",
  "Teko|s|15",
  "Hanken Grotesk|s|15",
  "Gravitas One|d|1",
  "Mukta|s|15",
  "Asap|s|15",
  "Bodoni Moda|r|15",
  "DM Mono|m|3",
  "Abel|s|1",
  "Maven Pro|s|15",
  "Chakra Petch|s|15",
  "Cabin|s|15",
  "M PLUS 1p|s|11",
  "Questrial|s|1",
  "Play|s|9",
  "Archivo Narrow|s|15",
  "Almarai|s|9",
  "Alumni Sans|s|15",
  "Caveat|h|15",
  "Abril Fatface|d|1",
  "Albert Sans|s|15",
  "Dosis|s|15",
  "Indie Flower|h|1",
  "Exo|s|15",
  "Geist|s|15",
  "Great Vibes|h|1",
  "Red Hat Display|s|15",
  "IBM Plex Serif|r|15",
  "Onest|s|15",
  "Spectral|r|15",
  "IBM Plex Sans Arabic|s|15",
  "Noto Sans Khmer|s|15",
  "Syne|s|15",
  "Cormorant|r|15",
  "M PLUS Rounded 1c|s|11",
  "Unbounded|s|15",
  "Sanchez|r|1",
  "Sofia Sans|s|15",
  "Nanum Myeongjo|r|9",
  "Epilogue|s|15",
  "Hind|s|15",
  "Oleo Script|d|9",
  "Zeyada|h|1",
  "Roboto Serif|r|15",
  "Permanent Marker|h|1",
  "Noto Serif TC|r|15",
  "Saira Condensed|s|15",
  "Noto Serif KR|r|15",
  "Ramabhadra|s|1",
  "Vollkorn|r|15",
  "Noto Kufi Arabic|s|15",
  "Amiri|r|9",
  "Encode Sans|s|15",
  "Noto Serif SC|r|15",
  "Sarabun|s|15",
  "Fira Code|m|15",
  "Faustina|r|15",
  "Noto Sans Devanagari|s|15",
  "Literata|r|15",
  "Delius|h|1",
  "Lobster|d|1",
  "Catamaran|s|15",
  "Press Start 2P|d|1",
  "Courier Prime|m|9",
  "Fira Sans Condensed|s|15",
  "Noto Sans Thai|s|15",
  "Red Hat Text|s|15",
  "Domine|r|15",
  "Russo One|s|1",
  "Cardo|r|9",
  "Noto Sans Arabic|s|15",
  "Tinos|r|9",
  "Asap Condensed|s|15",
  "Noto Naskh Arabic|r|15",
  "Chivo|s|15",
  "DM Serif Text|r|1",
  "Bree Serif|r|1",
  "Righteous|d|1",
  "Shadows Into Light|h|1",
  "Yellowtail|h|1",
  "Geist Mono|m|15",
  "Playfair|r|15",
  "Baskervville|r|15",
  "Acme|s|1",
  "Yanone Kaffeesatz|s|15",
  "Prata|r|1",
  "Shippori Mincho|r|15",
  "Space Mono|m|9",
  "ABeeZee|s|1",
  "Rowdies|d|9",
  "Fugaz One|d|1",
  "Lexend Deca|s|15",
  "Hammersmith One|s|1",
  "Kumbh Sans|s|15",
  "Zilla Slab|r|15",
  "Alegreya|r|15",
  "Zen Kaku Gothic New|s|11",
  "Satisfy|h|1",
  "Tenor Sans|s|1",
  "Cantarell|s|9",
  "Antic Slab|r|1",
  "Hind Madurai|s|15",
  "PT Mono|m|1",
  "Paytone One|s|1",
  "Bangers|d|1",
  "Rethink Sans|s|15",
  "Varela Round|s|1",
  "Be Vietnam Pro|s|15",
  "Old Standard TT|r|9",
  "Comic Neue|h|9",
  "Changa|s|15",
  "Allura|h|1",
  "Advent Pro|s|15",
  "VT323|m|1",
  "Khand|s|15",
  "League Spartan|s|15",
  "Audiowide|d|1",
  "Marcellus|r|1",
  "Noticia Text|r|9",
  "Patrick Hand|h|1",
  "Chelsea Market|d|1",
  "Quantico|s|9",
  "Crete Round|r|1",
  "STIX Two Text|r|15",
  "Sawarabi Gothic|s|1",
  "Atkinson Hyperlegible|s|9",
  "Quattrocento|r|9",
  "Sacramento|h|1",
  "Commissioner|s|15",
  "Geologica|s|15",
  "Lexend Giga|s|15",
  "Share Tech Mono|m|1",
  "Passion One|d|9",
  "Noto Nastaliq Urdu|r|15",
  "Antonio|s|15",
  "Radio Canada|s|15",
  "Crimson Pro|r|15",
  "Didact Gothic|s|1",
  "Philosopher|s|9",
  "Zen Maru Gothic|s|11",
  "Frank Ruhl Libre|r|15",
  "Martel|r|13",
  "Actor|s|1",
  "Kalam|h|9",
  "Yantramanav|s|11",
  "Josefin Slab|r|15",
  "Titan One|d|1",
  "Gruppo|s|1",
  "Francois One|s|1",
  "LINE Seed JP|s|9",
  "Oxanium|d|15",
  "Rokkitt|r|15",
  "Noto Sans HK|s|15",
  "Sofia Sans Condensed|s|15",
  "Baloo 2|d|15",
  "Signika Negative|s|15",
  "Rock Salt|h|1",
  "Signika|s|15",
  "Kosugi Maru|s|1",
  "Luckiest Guy|d|1",
  "Noto Sans Hebrew|s|15",
  "Architects Daughter|h|1",
  "Neuton|r|9",
  "Noto Sans Tamil|s|15",
  "Bai Jamjuree|s|15",
  "Homemade Apple|h|1",
  "Alex Brush|h|1",
  "Encode Sans Condensed|s|15",
  "Andada Pro|r|15",
  "Gabarito|d|15",
  "Alegreya Sans|s|11",
  "Tangerine|h|9",
  "Jura|s|15",
  "Quattrocento Sans|s|9",
  "Cookie|h|1",
  "Krub|s|15",
  "Amaranth|s|9",
  "Viga|s|1",
  "M PLUS 1|s|15",
  "Dela Gothic One|d|1",
  "Montserrat Alternates|s|15",
  "Forum|d|1",
  "Golos Text|s|15",
  "Istok Web|s|9",
  "Rammetto One|d|1",
  "Berkshire Swash|h|1",
  "News Cycle|s|9",
  "Yeseva One|d|1",
  "Playball|d|1",
  "Pathway Gothic One|s|1",
  "Andika|s|9",
  "El Messiri|s|15",
  "Monoton|d|1",
  "Italianno|h|1",
  "Libre Barcode 39|d|1",
  "Radio Canada Big|s|15",
  "Fira Mono|m|11",
  "Eater|d|1",
  "Staatliches|d|1",
  "Blinker|s|13",
  "Gothic A1|s|15",
  "Hind Guntur|s|15",
  "Cinzel Decorative|d|9",
  "Goldman|d|9",
  "Readex Pro|s|15",
  "Damion|h|1",
  "Aleo|r|15",
  "Saira Extra Condensed|s|15",
  "Amatic SC|h|9",
  "Caveat Brush|h|1",
  "Google Sans Code|m|15",
  "Alata|s|1",
  "Nothing You Could Do|h|1",
  "Noto Sans Display|s|15",
  "Ubuntu Sans|s|15",
  "Courgette|h|1",
  "Petrona|r|15",
  "IBM Plex Sans Condensed|s|15",
  "Michroma|s|1",
  "Noto Serif Bengali|r|15",
  "Angkor|d|1",
  "Sorts Mill Goudy|r|1",
  "Mona Sans|s|15",
  "Noto Sans Mono|s|15",
  "Monda|s|15",
  "Atkinson Hyperlegible Next|s|15",
  "BIZ UDPGothic|s|9",
  "Anonymous Pro|m|9",
  "Kaushan Script|h|1",
  "Ropa Sans|s|1",
  "Vidaloka|r|1",
  "Averia Serif Libre|d|9",
  "Georama|s|15",
  "Special Elite|d|1",
  "Cuprum|s|15",
  "IBM Plex Sans Thai|s|15",
  "REM|s|15",
  "Syncopate|s|9",
  "Saira Semi Condensed|s|15",
  "Mr Dafoe|h|1",
  "Fira Sans Extra Condensed|s|15",
  "Sawarabi Mincho|r|1",
  "Afacad|s|15",
  "Libre Caslon Text|r|9",
  "Creepster|d|1",
  "Racing Sans One|d|1",
  "Cousine|m|9",
  "Gloria Hallelujah|h|1",
  "Mrs Saint Delafield|h|1",
  "Patua One|d|1",
  "Varela|s|1",
  "Bad Script|h|1",
  "Noto Serif Display|r|15",
  "Calistoga|d|1",
  "Funnel Sans|s|15",
  "Reddit Sans|s|15",
  "Secular One|s|1",
  "Balsamiq Sans|d|9",
  "M PLUS 2|s|15",
  "Caprasimo|d|1",
  "Noto Sans Bengali|s|15",
  "IBM Plex Sans JP|s|15",
  "Economica|s|9",
  "Gochi Hand|h|1",
  "Mukta Malar|s|15",
  "Ruda|s|15",
  "Cabin Condensed|s|15",
  "La Belle Aurore|h|1",
  "Squada One|d|1",
  "Comic Relief|d|9",
  "Sen|s|15",
  "Sofia|h|1",
  "Carter One|d|1",
  "Zen Old Mincho|r|15",
  "Potta One|d|1",
  "Spline Sans|s|15",
  "Martel Sans|s|13",
  "Anek Bangla|s|15",
  "Limelight|d|1",
  "Alexandria|s|15",
  "Belanosima|s|13",
  "Knewave|d|1",
  "League Gothic|s|1",
  "Aboreto|d|1",
  "PT Sans Caption|s|9",
  "Covered By Your Grace|h|1",
  "Pangolin|h|1",
  "Rye|d|1",
  "Itim|h|1",
  "Hachi Maru Pop|h|1",
  "Rubik Mono One|s|1",
  "Overpass Mono|m|15",
  "Big Shoulders|d|15",
  "Do Hyeon|s|1",
  "Funnel Display|d|15",
  "Leckerli One|h|1",
  "Akshar|s|15",
  "Nanum Gothic Coding|h|9",
  "Fustat|s|15",
  "Sarala|s|9",
  "Vazirmatn|s|15",
  "Suez One|r|1",
  "Grandstander|d|15",
  "Boogaloo|d|1",
  "Geo|s|1",
  "Ubuntu Condensed|s|1",
  "Cedarville Cursive|h|1",
  "Germania One|d|1",
  "Italiana|s|1",
  "Unna|r|9",
  "Palanquin Dark|s|15",
  "Playfair Display SC|r|9",
  "Wix Madefor Text|s|15",
  "Tilt Warp|d|1",
  "Khula|s|13",
  "Sansita|s|9",
  "Gilda Display|r|1",
  "Shrikhand|d|1",
  "Rufina|r|9",
  "Fahkwang|s|15",
  "Baloo Da 2|d|15",
  "Ma Shan Zheng|h|1",
  "Darker Grotesque|s|15",
  "Nixie One|d|1",
  "Charm|h|9",
  "Mate|r|1",
  "Parkinsans|s|15",
  "Poiret One|d|1",
  "Gloock|r|1",
  "Gantari|s|15",
  "Yuji Mai|r|1",
  "Pontano Sans|s|15",
  "Libre Barcode 128|d|1",
  "Lustria|r|1",
  "Noto Sans Gujarati|s|15",
  "Reenie Beanie|h|1",
  "Pinyon Script|h|1",
  "UnifrakturMaguntia|d|1",
  "Playpen Sans|h|15",
  "Marcellus SC|r|1",
  "Tomorrow|s|15",
  "Fragment Mono|m|1",
  "Libre Bodoni|r|15",
  "Coda|d|1",
  "Sintony|s|9",
  "Proza Libre|s|15",
  "Kiwi Maru|r|3",
  "Nanum Pen Script|h|1",
  "Arsenal|s|9",
  "Libre Caslon Display|r|1",
  "Chonburi|d|1",
  "Eczar|r|15",
  "Corben|d|9",
  "Basic|s|1",
  "Concert One|d|1",
  "Oooh Baby|h|1",
  "Abhaya Libre|r|15",
  "BIZ UDGothic|s|9",
  "Livvic|s|15",
  "Noto Sans Malayalam|s|15",
  "Radley|r|1",
  "Chango|d|1",
  "Red Hat Mono|m|15",
  "Neucha|h|1",
  "K2D|s|15",
  "Vina Sans|d|1",
  "Ibarra Real Nova|r|15",
  "Mitr|s|15",
  "IBM Plex Sans KR|s|15",
  "Judson|r|9",
  "Trirong|r|15",
  "Gelasio|r|15",
  "Tektur|d|15",
  "Abyssinica SIL|r|1",
  "Merienda|h|15",
  "Noto Sans Georgian|s|15",
  "Glegoo|r|9",
  "Yatra One|d|1",
  "Pixelify Sans|d|15",
  "Bowlby One|d|1",
  "Lusitana|r|9",
  "PT Serif Caption|r|1",
  "Castoro|r|1",
  "Armata|s|1",
  "Biryani|s|13",
  "Caudex|r|9",
  "Cutive Mono|m|1",
  "Young Serif|r|1",
  "Dawning of a New Day|h|1",
  "Noto Sans Myanmar|s|15",
  "Tiro Bangla|r|1",
  "Graduate|r|1",
  "Azeret Mono|m|15",
  "Carlito|s|9",
  "Pattaya|s|1",
  "Lalezar|s|1",
  "Share|s|9",
  "Alef|s|9",
  "Cantata One|r|1",
  "Jua|s|1",
  "Herr Von Muellerhoff|h|1",
  "Ubuntu Mono|m|9",
  "ZCOOL XiaoWei|s|1",
  "Podkova|r|15",
  "Volkhov|r|9",
  "Athiti|s|15",
  "Metrophobic|s|1",
  "Bellefair|r|1",
  "Lateef|r|15",
  "Parisienne|h|1",
  "Enriqueta|r|15",
  "Handlee|h|1",
  "Nova Square|d|1",
  "Sriracha|h|1",
  "Petit Formal Script|h|1",
  "Unica One|d|1",
  "AR One Sans|s|15",
  "Cormorant Infant|r|15",
  "Noto Sans Kannada|s|15",
  "TikTok Sans|s|15",
  "Averia Libre|d|9",
  "GFS Didot|r|1",
  "Laila|r|15",
  "Noto Sans Gurmukhi|s|15",
  "Cormorant Upright|r|15",
  "Belleza|s|1",
  "Spinnaker|s|1",
  "Chiron GoRound TC|s|15",
  "Black Han Sans|s|1",
  "Norican|h|1",
  "Zalando Sans|s|15",
  "Lexend Peta|s|15",
  "Nanum Brush Script|h|1",
  "Allison|h|1",
  "Telex|s|1",
  "Hind Vadodara|s|15",
  "Libre Barcode 39 Text|d|1",
  "Glory|s|15",
  "Bentham|r|1",
  "Host Grotesk|s|15",
  "Hina Mincho|r|1",
  "Lexend Zetta|s|15",
  "Karma|r|15",
  "Klee One|h|5",
  "Nobile|s|11",
  "BIZ UDPMincho|r|9",
  "Besley|r|15",
  "Koulen|d|1",
  "Gaegu|h|9",
  "Pathway Extreme|s|15",
  "Special Gothic|s|15",
  "Corinthia|h|9",
  "Ms Madi|h|1",
  "BioRhyme|r|15",
  "Mouse Memoirs|s|1",
  "Schoolbell|h|1",
  "Markazi Text|r|15",
  "Sometype Mono|m|15",
  "Anton SC|s|1",
  "Amiko|s|13",
  "Calligraffitti|h|1",
  "Rampart One|d|1",
  "Average Sans|s|1",
  "Sofia Sans Extra Condensed|s|15",
  "Alice|r|1",
  "Fjord One|r|1",
  "Arapey|r|1",
  "Sniglet|d|1",
  "Pragati Narrow|s|9",
  "Special Gothic Condensed One|s|1",
  "Monomaniac One|s|1",
  "Julius Sans One|s|1",
  "ZCOOL KuaiLe|s|1",
  "Alatsi|s|1",
  "Mada|s|15",
  "Inria Sans|s|9",
  "Zen Kaku Gothic Antique|s|11",
  "Recursive|s|15",
  "Skranji|d|9",
  "Amita|h|9",
  "Kodchasan|s|15",
  "IM Fell English SC|r|1",
  "Gudea|s|9",
  "Noto Serif Georgian|r|15",
  "Ledger|r|1",
  "Meow Script|h|1",
  "Sedgwick Ave Display|h|1",
  "Shippori Mincho B1|r|15",
  "Allerta|s|1",
  "Dongle|s|9",
  "Overlock|d|9",
  "Familjen Grotesk|s|15",
  "Tilt Neon|d|1",
  "Pridi|r|15",
  "Waiting for the Sunrise|h|1",
  "Cormorant Unicase|r|15",
  "Reem Kufi|s|15",
  "Monsieur La Doulaise|h|1",
  "Oxygen Mono|m|1",
  "Shantell Sans|d|15",
  "Taviraj|r|15",
  "Kaisei Decol|r|11",
  "Over the Rainbow|h|1",
  "Flow Circular|d|1",
  "Bubblegum Sans|d|1",
  "Love Ya Like A Sister|d|1",
  "Ultra|r|1",
  "Encode Sans Expanded|s|15",
  "Major Mono Display|m|1",
  "Six Caps|s|1",
  "Marck Script|h|1",
  "Megrim|d|1",
  "Wix Madefor Display|s|15",
  "Yesteryear|h|1",
  "Metamorphous|d|1",
  "Pirata One|d|1",
  "Meddon|h|1",
  "Croissant One|d|1",
  "Lemonada|d|15",
  "Magra|s|9",
  "Poetsen One|d|1",
  "Palanquin|s|15",
  "Syne Mono|m|1",
  "Faster One|d|1",
  "Just Another Hand|h|1",
  "Kelly Slab|d|1",
  "Red Rose|d|15",
  "Alegreya Sans SC|s|11",
  "Kantumruy Pro|s|15",
  "Libertinus Serif|r|13",
  "IBM Plex Sans Hebrew|s|15",
  "Murecho|s|15",
  "Quintessential|h|1",
  "Grenze Gotisch|d|15",
  "Niramit|s|15",
  "Zen Kurenaido|s|1",
  "Londrina Solid|d|1",
  "Noto Sans Thai Looped|s|15",
  "Zen Antique|r|1",
  "Akatab|s|15",
  "Bayon|s|1",
  "Baloo Thambi 2|d|15",
  "MedievalSharp|d|1",
  "Hurricane|h|1",
  "Rozha One|r|1",
  "David Libre|r|11",
  "Cambay|s|9",
  "MuseoModerno|d|15",
  "Turret Road|d|11",
  "Carrois Gothic|s|1",
  "Agbalumo|d|1",
  "Inknut Antiqua|r|15",
  "Noto Sans Symbols|s|15",
  "Voltaire|s|1",
  "Scada|s|9",
  "Poller One|d|1",
  "Gotu|s|1",
  "Special Gothic Expanded One|s|1",
  "KoHo|s|15",
  "B612 Mono|m|9",
  "Baloo Bhai 2|d|15",
  "Bowlby One SC|d|1",
  "Bungee Inline|d|1",
  "Mandali|s|1",
  "Manjari|s|9",
  "Beth Ellen|h|1",
  "Bevan|r|1",
  "Adamina|r|1",
  "Rubik Dirt|d|1",
  "Rochester|h|1",
  "Libre Barcode 39 Extended|d|1",
  "Bungee Spice|d|1",
  "Chewy|d|1",
  "Hanuman|r|15",
  "Elsie|d|1",
  "Kaisei Opti|r|11",
  "Slackey|d|1",
  "Bungee Shade|d|1",
  "Miriam Libre|s|15",
  "Mukta Mahee|s|15",
  "Qwigley|h|1",
  "Averia Sans Libre|d|9",
  "Noto Sans Warang Citi|s|1",
  "Mali|h|15",
  "Rambla|s|9",
  "Average|r|1",
  "Stardos Stencil|d|9",
  "Gurajada|s|1",
  "Kreon|r|15",
  "Mansalva|h|1",
  "Baloo Bhaijaan 2|d|15",
  "Spectral SC|r|15",
  "Ruslan Display|d|1",
  "SUSE|s|15",
  "Gluten|d|15",
  "IM Fell English|r|1",
  "Inder|s|1",
  "Aldrich|s|1",
  "Doppio One|s|1",
  "Jomhuria|d|1",
  "Days One|s|1",
  "Slabo 13px|r|1",
  "B612|s|9",
  "Moon Dance|h|1",
  "Padauk|s|9",
  "Cherry Bomb One|d|1",
  "Vast Shadow|r|1",
  "Kurale|r|1",
  "Contrail One|d|1",
  "Zain|s|9",
  "Oleo Script Swash Caps|d|9",
  "Sunflower|s|10",
  "Yrsa|r|15",
  "Cabin Sketch|d|9",
  "Trispace|s|15",
  "Capriola|s|1",
  "BenchNine|s|9",
  "Whisper|h|1",
  "Piazzolla|r|15",
  "Jaldi|s|9",
  "Krona One|s|1",
  "Niconne|h|1",
  "Thasadith|s|9",
  "Encode Sans Semi Expanded|s|15",
  "Ovo|r|1",
  "Sedgwick Ave|h|1",
  "Sarina|d|1",
  "Vesper Libre|r|11",
  "Noto Serif Khojki|r|15",
  "Fredericka the Great|d|1",
  "Mr De Haviland|h|1",
  "UnifrakturCook|d|8",
  "Puritan|s|9",
  "Lacquer|d|1",
  "Alike|r|1",
  "Barriecito|d|1",
  "Allan|d|9",
  "Reddit Sans Condensed|s|15",
  "Afacad Flux|s|15",
  "Euphoria Script|h|1",
  "Metal Mania|d|1",
  "Noto Sans Ethiopic|s|15",
  "Shadows Into Light Two|h|1",
  "Raleway Dots|d|1",
  "Anek Latin|s|15",
  "Montez|h|1",
  "Charis SIL|r|9",
  "Oregano|d|1",
  "Prosto One|d|1",
  "Alike Angular|r|1",
  "Brawler|r|9",
  "Quando|r|1",
  "Qwitcher Grypen|h|9",
  "League Script|h|1",
  "Nata Sans|s|15",
  "Noto Sans Sinhala|s|15",
  "Patrick Hand SC|h|1",
  "Freehand|d|1",
  "Tenali Ramakrishna|s|1",
  "Borel|h|1",
  "Zen Antique Soft|r|1",
  "Jersey 25|d|1",
  "MonteCarlo|h|1",
  "Shojumaru|d|1",
  "Fuggles|h|1",
  "Gowun Batang|r|9",
  "Vollkorn SC|r|13",
  "Finger Paint|d|1",
  "Kalnia|r|15",
  "Redressed|h|1",
  "Noto Sans Meetei Mayek|s|15",
  "Rubik Glitch|d|1",
  "Chivo Mono|m|15",
  "Stick No Bills|s|15",
  "Anuphan|s|15",
  "Prociono|r|1",
  "Protest Revolution|d|1",
  "Bakbak One|d|1",
  "Tienne|r|9",
  "Cambo|r|1",
  "Scope One|r|1",
  "Cherry Cream Soda|d|1",
  "Aclonica|s|1",
  "Molengo|s|1",
  "Unkempt|d|9",
  "Modak|d|1",
  "Gulzar|r|1",
  "BhuTuka Expanded One|r|1",
  "Suranna|r|1",
  "Electrolize|s|1",
  "Kranky|d|1",
  "Kosugi|s|1",
  "The Girl Next Door|h|1",
  "Train One|d|1",
  "Federo|s|1",
  "Anta|s|1",
  "Ruwudu|r|15",
  "Carattere|h|1",
  "Inria Serif|r|9",
  "Mallanna|s|1",
  "Trade Winds|d|1",
  "Freeman|d|1",
  "Imprima|s|1",
  "The Nautigal|h|9",
  "Sansation|s|9",
  "Wire One|s|1",
  "Licorice|h|1",
  "Sail|d|1",
  "Artifika|r|1",
  "Kameron|r|15",
  "Sunshiney|h|1",
  "Hepta Slab|r|15",
  "Iceberg|d|1",
  "DotGothic16|s|1",
  "Shippori Antique|s|1",
  "Antic|s|1",
  "IM Fell French Canon|r|1",
  "Candal|s|1",
  "Henny Penny|d|1",
  "Frijole|d|1",
  "Oranienbaum|r|1",
  "IM Fell Double Pica|r|1",
  "Galindo|d|1",
  "Cal Sans|s|1",
  "Port Lligat Sans|s|1",
  "Luxurious Script|h|1",
  "Style Script|h|1",
  "Cairo Play|s|15",
  "Brygada 1918|r|15",
  "Noto Sans Sundanese|s|15",
  "Sofia Sans Semi Condensed|s|15",
  "TASA Orbiter|s|15",
  "Bona Nova SC|r|9",
  "Mohave|s|15",
  "Anaheim|s|15",
  "Original Surfer|d|1",
  "IM Fell Great Primer|r|1",
  "Lexend Exa|s|15",
  "Fresca|s|1",
  "IBM Plex Sans Thai Looped|s|15",
  "Zalando Sans Expanded|s|15",
  "Noto Serif HK|r|15",
  "Asta Sans|s|15",
  "Spline Sans Mono|m|15",
  "Arbutus Slab|r|1",
  "Rationale|s|1",
  "Duru Sans|s|1",
  "Bellota|d|9",
  "Spicy Rice|d|1",
  "Grand Hotel|h|1",
  "Manuale|r|15",
  "Grenze|r|15",
  "Antic Didone|r|1",
  "Imbue|r|15",
  "Atomic Age|d|1",
  "Gugi|d|1",
  "Seaweed Script|d|1",
  "Caladea|r|9",
  "Loved by the King|h|1",
  "Faculty Glyphic|s|1",
  "Tiro Devanagari Hindi|r|1",
  "Montagu Slab|r|15",
  "Nokora|s|15",
  "Clicker Script|h|1",
  "Swanky and Moo Moo|h|1",
  "Long Cang|h|1",
  "Rakkas|d|1",
  "Mooli|s|1",
  "ADLaM Display|d|1",
  "Kaisei Tokumin|r|11",
  "Viaoda Libre|d|1",
  "Ranchers|d|1",
  "Karantina|d|9",
  "Nova Round|d|1",
  "Doto|s|15",
  "Marvel|s|9",
  "Science Gothic|s|15",
  "Gasoek One|s|1",
  "Rancho|h|1",
  "Allerta Stencil|s|1",
  "Amethysta|r|1",
  "Emilys Candy|d|1",
  "Cormorant SC|r|15",
  "Gentium Book Plus|r|9",
  "Smythe|d|1",
  "NTR|s|1",
  "Birthstone Bounce|h|3",
  "Headland One|r|1",
  "Dokdo|d|1",
  "Varta|s|15",
  "Zhi Mang Xing|h|1",
  "Chicle|d|1",
  "Coming Soon|h|1",
  "Harmattan|s|15",
  "Bitcount Single|d|15",
  "Montaga|r|1",
  "Comme|s|15",
  "Mina|s|9",
  "Jaro|s|1",
  "Vujahday Script|h|1",
  "Stack Sans Text|s|15",
  "M PLUS 1 Code|m|15",
  "Fenix|r|1",
  "Rubik Spray Paint|d|1",
  "Kdam Thmor Pro|s|1",
  "Silkscreen|d|9",
  "Alegreya SC|r|11",
  "Momo Trust Sans|s|15",
  "Voces|s|1",
  "Gayathri|s|9",
  "Wallpoet|d|1",
  "Badeen Display|d|1",
  "BIZ UDMincho|r|9",
  "Sigmar One|d|1",
  "Alkalami|r|1",
  "Rosario|s|15",
  "Idiqlat|r|1",
  "Halant|r|15",
  "Lovers Quarrel|h|1",
  "Lavishly Yours|h|1",
  "Mynerve|h|1",
  "Hahmlet|r|15",
  "Homenaje|s|1",
  "Convergence|s|1",
  "Marmelad|s|1",
  "Galada|d|1",
  "Goudy Bookletter 1911|r|1",
  "DynaPuff|d|15",
  "Geom|s|15",
  "Irish Grover|d|1",
  "Peralta|r|1",
  "Asset|d|1",
  "Gabriela|r|1",
  "Delius Swash Caps|h|1",
  "Lemon|d|1",
  "Nova Oval|d|1",
  "Kristi|h|1",
  "Mea Culpa|h|1",
  "Engagement|h|1",
  "Kode Mono|m|15",
  "IBM Plex Sans Devanagari|s|15",
  "Baloo Bhaina 2|d|15",
  "Mochiy Pop One|s|1",
  "Noto Sans Bhaiksuki|s|1",
  "Mozilla Headline|s|15",
  "Carme|s|1",
  "Noto Sans Oriya|s|15",
  "Gemunu Libre|s|15",
  "Anek Tamil|s|15",
  "Arizonia|h|1",
  "Strait|s|1",
  "Habibi|r|1",
  "Ysabeau|s|15",
  "Annie Use Your Telescope|h|1",
  "Redacted|d|1",
  "Girassol|d|1",
  "Miltonian|d|1",
  "Imperial Script|h|1",
  "Rouge Script|h|1",
  "Amiri Quran|r|1",
  "Fondamento|h|1",
  "Donegal One|r|1",
  "Kapakana|h|1",
  "Solitreo|h|1",
  "Baskervville SC|r|15",
  "Elms Sans|s|15",
  "Chau Philomene One|s|1",
  "LXGW WenKai TC|h|9",
  "Belgrano|r|1",
  "Lekton|m|9",
  "Ceviche One|d|1",
  "RocknRoll One|s|1",
  "Akronim|d|1",
  "Anybody|d|15",
  "Londrina Outline|d|1",
  "Macondo|d|1",
  "Nova Cut|d|1",
  "IM Fell Great Primer SC|r|1",
  "Pompiere|d|1",
  "Timmana|s|1",
  "Marhey|d|15",
  "Dangrek|d|1",
  "Sevillana|d|1",
  "Yusei Magic|s|1",
  "Cherry Swash|d|9",
  "Akaya Kanadaka|d|1",
  "Mountains of Christmas|d|9",
  "Fanwood Text|r|1",
  "Noto Sans Samaritan|s|1",
  "Noto Music|s|1",
  "Tauri|s|1",
  "Trocchi|r|1",
  "Miltonian Tattoo|d|1",
  "Zen Dots|d|1",
  "Chocolate Classical Sans|s|1",
  "Sigmar|d|1",
  "Tillana|d|15",
  "Stalemate|h|1",
  "Erica One|d|1",
  "Unlock|d|1",
  "Freckle Face|d|1",
  "Hi Melody|h|1",
  "Water Brush|h|1",
  "Barrio|d|1",
  "Noto Serif Devanagari|r|15",
  "Hedvig Letters Sans|s|1",
  "Stint Ultra Condensed|r|1",
  "Pavanam|s|1",
  "Gowun Dodum|s|1",
  "Sree Krushnadevaraya|r|1",
  "Zilla Slab Highlight|r|9",
  "Asul|r|9",
  "Edu NSW ACT Cursive|h|15",
  "Margarine|d|1",
  "Sura|r|9",
  "Ballet|h|1",
  "Liter|s|1",
  "Fascinate|d|1",
  "Mystery Quest|d|1",
  "Nova Script|d|1",
  "Rubik Doodle Shadow|d|1",
  "Stylish|s|1",
  "Cantora One|s|1",
  "Maitree|r|15",
  "Yeon Sung|d|1",
  "Stint Ultra Expanded|r|1",
  "Bilbo|h|1",
  "Platypi|r|15",
  "Akaya Telivigala|d|1",
  "Lexend Mega|s|15",
  "Carrois Gothic SC|s|1",
  "Noto Serif Thai|r|15",
  "Katibeh|d|1",
  "Fascinate Inline|d|1",
  "Inclusive Sans|s|15",
  "National Park|s|15",
  "Benne|r|1",
  "Shippori Antique B1|s|1",
  "Yuji Syuku|r|1",
  "Copse|r|1",
  "Passions Conflict|h|1",
  "Hedvig Letters Serif|r|1",
  "Noto Serif Hebrew|r|15",
  "Jacques Francois|r|1",
  "Nova Mono|m|1",
  "Island Moments|h|1",
  "Zen Tokyo Zoo|d|1",
  "Suwannaphum|r|9",
  "Dekko|h|1",
  "Birthstone|h|1",
  "Simonetta|d|1",
  "Griffy|d|1",
  "Noto Sans Tagalog|s|1",
  "Risque|d|1",
  "Noto Sans Tai Viet|s|1",
  "Bellota Text|d|9",
  "Noto Serif Tamil|r|15",
  "Geostar Fill|d|1",
  "McLaren|d|1",
  "Romanesco|h|1",
  "Sansita Swashed|d|15",
  "Offside|d|1",
  "SN Pro|s|15",
  "Akt|s|15",
  "Short Stack|h|1",
  "Ancizar Serif|r|15",
  "Anek Devanagari|s|15",
  "Atkinson Hyperlegible Mono|s|15",
  "Fuzzy Bubbles|h|9",
  "Almendra|r|9",
  "Jim Nightshade|h|1",
  "Story Script|s|1",
  "Baloo Tamma 2|d|15",
  "Tourney|d|15",
  "Handjet|d|15",
  "Encode Sans Semi Condensed|s|15",
  "Noto Serif Telugu|r|15",
  "Rubik Scribble|d|1",
  "Zalando Sans SemiExpanded|s|15",
  "Bruno Ace SC|d|1",
  "Happy Monkey|d|1",
  "Manufacturing Consent|d|1",
  "Scheherazade New|r|15",
  "Caramel|h|1",
  "Jacquard 12|d|1",
  "Vend Sans|s|15",
  "ZCOOL QingKe HuangYou|s|1",
  "Linden Hill|r|1",
  "Poor Story|d|1",
  "Fasthand|d|1",
  "Gwendolyn|h|9",
  "Aref Ruqaa|r|9",
  "Elsie Swash Caps|d|1",
  "Inika|r|9",
  "Mukta Vaani|s|15",
  "Seymour One|s|1",
  "Beiruti|s|15",
  "Crafty Girls|h|1",
  "Montserrat Underline|s|15",
  "Sahitya|r|9",
  "Anek Odia|s|15",
  "Butterfly Kids|h|1",
  "Spirax|d|1",
  "Underdog|d|1",
  "Noto Sans Buhid|s|1",
  "Farro|s|11",
  "Ysabeau Infant|s|15",
  "Noto Sans Canadian Aboriginal|s|15",
  "Fauna One|r|1",
  "Orbit|s|1",
  "Square Peg|h|1",
  "Edu AU VIC WA NT Hand|h|15",
  "Glass Antiqua|d|1",
  "Autour One|d|1",
  "Wittgenstein|r|15",
  "Xanh Mono|m|1",
  "Ruluko|s|1",
  "Rubik Moonrocks|d|1",
  "Boldonse|d|1",
  "Castoro Titling|d|1",
  "Send Flowers|h|1",
  "Martian Mono|m|15",
  "New Tegomin|r|1",
  "Farsan|d|1",
  "IM Fell DW Pica|r|1",
  "Tiro Devanagari Marathi|r|1",
  "Mogra|d|1",
  "Jacques Francois Shadow|d|1",
  "Inspiration|h|1",
  "Noto Sans Ol Chiki|s|15",
  "Uchen|r|1",
  "Kite One|s|1",
  "Noto Sans Gothic|s|1",
  "Chathura|s|9",
  "Aguafina Script|h|1",
  "Festive|h|1",
  "Battambang|d|9",
  "Oi|d|1",
  "Big Shoulders Stencil|d|15",
  "Solway|r|11",
  "Nuosu SIL|s|1",
  "Asar|r|1",
  "Praise|h|1",
  "Ewert|d|1",
  "Give You Glory|h|1",
  "Momo Signature|s|1",
  "Vibur|h|1",
  "Plaster|d|1",
  "Poly|r|1",
  "Diplomata|d|1",
  "Sue Ellen Francisco|h|1",
  "Kadwa|r|9",
  "Marko One|r|1",
  "Luxurious Roman|d|1",
  "Noto Sans Symbols 2|s|1",
  "Rubik Iso|d|1",
  "Tiro Tamil|r|1",
  "Gideon Roman|d|1",
  "Noto Sans Thaana|s|15",
  "Alumni Sans Inline One|d|1",
  "Grape Nuts|h|1",
  "Ephesis|h|1",
  "Sirin Stencil|d|1",
  "Princess Sofia|h|1",
  "Odor Mean Chey|r|1",
  "Babylonica|h|1",
  "Reem Kufi Ink|s|1",
  "Noto Serif Khmer|r|15",
  "Noto Sans Lao|s|15",
  "SUSE Mono|s|15",
  "Miss Fajardose|h|1",
  "WDXL Lubrifont JP N|s|1",
  "Coustard|r|1",
  "Sixtyfour|m|1",
  "Noto Sans Osmanya|s|1",
  "Anek Gurmukhi|s|15",
  "Sofadi One|d|1",
  "Noto Rashi Hebrew|r|15",
  "Meera Inimai|s|1",
  "Joti One|d|1",
  "Lakki Reddy|h|1",
  "Codystar|d|1",
  "Intel One Mono|m|15",
  "Aref Ruqaa Ink|r|9",
  "Coiny|d|1",
  "Jersey 15|d|1",
  "Rubik Distressed|d|1",
  "Peddana|r|1",
  "Londrina Sketch|d|1",
  "Dhurjati|s|1",
  "Fontdiner Swanky|d|1",
  "Bonbon|h|1",
  "Balthazar|r|1",
  "Noto Sans Javanese|s|15",
  "Arsenal SC|s|9",
  "Della Respira|r|1",
  "Ribeye Marrow|d|1",
  "Alyamama|r|15",
  "Jockey One|s|1",
  "Felipa|h|1",
  "Numans|s|1",
  "Noto Sans Sora Sompeng|s|15",
  "Updock|h|1",
  "Amarante|d|1",
  "Ojuju|s|15",
  "Bacasime Antique|r|1",
  "Passero One|d|1",
  "Neonderthaw|h|1",
  "Chela One|d|1",
  "Cutive|r|1",
  "Teachers|s|15",
  "Buenard|r|15",
  "Micro 5|d|1",
  "Revalia|d|1",
  "Walter Turncoat|h|1",
  "Tiro Kannada|r|1",
  "Syne Tactile|d|1",
  "Arima|d|15",
  "Ubuntu Sans Mono|m|15",
  "Diplomata SC|d|1",
  "Amarna|s|15",
  "Snippet|s|1",
  "Mr Bedfort|h|1",
  "Supermercado One|d|1",
  "Jacquarda Bastarda 9|d|1",
  "Grey Qo|h|1",
  "Ancizar Sans|s|15",
  "Gidugu|s|1",
  "Bilbo Swash Caps|h|1",
  "Preahvihear|s|1",
  "Expletus Sans|d|15",
  "Purple Purse|d|1",
  "Shizuru|d|1",
  "Noto Sans Adlam|s|15",
  "Noto Sans Armenian|s|15",
  "Jersey 20|d|1",
  "Bahiana|d|1",
  "Kings|h|1",
  "Foldit|d|15",
  "Diphylleia|r|1",
  "Lancelot|d|1",
  "Edu VIC WA NT Beginner|h|15",
  "Rasa|r|15",
  "Noto Serif Dives Akuru|r|1",
  "Slackside One|h|1",
  "Kolker Brush|h|1",
  "Ranga|d|9",
  "Cossette Titre|s|9",
  "BioRhyme Expanded|r|9",
  "New Rocker|d|1",
  "Gidole|s|1",
  "Cause|h|15",
  "Dynalight|d|1",
  "Valley Sans|s|15",
  "Sedan|r|1",
  "Rosarivo|r|1",
  "Sedan SC|r|1",
  "Rhodium Libre|r|1",
  "Charmonman|h|9",
  "Cherish|h|1",
  "Konkhmer Sleokchher|d|1",
  "Iansui|h|1",
  "Noto Sans Shavian|s|1",
  "Estedad|s|15",
  "Geist Pixel|d|1",
  "Love Light|h|1",
  "Hanalei Fill|d|1",
  "Noto Sans Vithkuqi|s|15",
  "Atma|d|15",
  "Menbere|s|15",
  "Flow Rounded|d|1",
  "Orienta|s|1",
  "Gupter|r|11",
  "Langar|d|1",
  "Mirza|r|15",
  "Sixtyfour Convergence|m|1",
  "Alkatra|d|15",
  "Cascadia Mono|s|15",
  "Gamja Flower|h|1",
  "Noto Sans Pahawh Hmong|s|1",
  "Aladin|d|1",
  "Rubik Burned|d|1",
  "Kufam|s|15",
  "Noto Serif Ethiopic|r|15",
  "Bagel Fat One|d|1",
  "Flow Block|d|1",
  "Splash|h|1",
  "Matemasie|s|1",
  "Estonia|h|1",
  "Sarpanch|s|15",
  "Blaka|d|1",
  "Noto Sans Cherokee|s|15",
  "Rubik Microbe|d|1",
  "Libre Barcode 39 Extended Text|d|1",
  "Triodion|d|1",
  "Noto Sans Sunuwar|s|1",
  "Noto Sans NKo|s|1",
  "Orelega One|d|1",
  "Black And White Picture|d|1",
  "Sulphur Point|s|9",
  "Rubik Vinyl|d|1",
  "Noto Sans Takri|s|1",
  "Noto Serif Vithkuqi|r|15",
  "Bitcount Grid Single|d|15",
  "Moul|d|1",
  "Geostar|d|1",
  "Narnoor|s|15",
  "Rubik Glitch Pop|d|1",
  "Nosifer|d|1",
  "Noto Sans Cypro Minoan|s|1",
  "Kalnia Glaze|d|15",
  "Noto Sans Old Permic|s|1",
  "Are You Serious|h|1",
  "WindSong|h|3",
  "Noto Sans Kaithi|s|1",
  "Ga Maamli|d|1",
  "Road Rage|d|1",
  "Rubik 80s Fade|d|1",
  "Epunda Slab|r|15",
  "Wendy One|s|1",
  "Protest Strike|d|1",
  "Phudu|d|15",
  "Rubik Beastly|d|1",
  "Anek Malayalam|s|15",
  "Edu AU VIC WA NT Dots|h|15",
  "Bigshot One|d|1",
  "Redacted Script|d|9",
  "Moo Lah Lah|d|1",
  "Lumanosimo|h|1",
  "Tiny5|s|1",
  "Kablammo|d|1",
  "Libertinus Mono|m|1",
  "Noto Sans Balinese|s|15",
  "Sassy Frass|h|1",
  "Song Myung|r|1",
  "Tai Heritage Pro|r|9",
  "Aoboshi One|r|1",
  "Sour Gummy|s|15",
  "Taprom|d|1",
  "Arya|s|9",
  "Noto Sans Nag Mundari|s|15",
  "Rubik Marker Hatch|d|1",
  "Noto Sans Coptic|s|1",
  "Noto Sans Yi|s|1",
  "Sancreek|d|1",
  "Coral Pixels|d|1",
  "Salsa|d|1",
  "Combo|d|1",
  "Reddit Mono|m|15",
  "Lilex|m|15",
  "Ysabeau Office|s|15",
  "Labrada|r|15",
  "Asimovian|s|1",
  "Qahiri|s|1",
  "Annapurna SIL|r|9",
  "Edu SA Beginner|h|15",
  "Edu AU VIC WA NT Guides|h|15",
  "Libertinus Sans|s|9",
  "Life Savers|d|9",
  "Noto Serif Balinese|r|1",
  "Reggae One|d|1",
  "Just Me Again Down Here|h|1",
  "Noto Sans Carian|s|1",
  "Darumadrop One|d|1",
  "Noto Sans Syriac|s|15",
  "Eagle Lake|h|1",
  "Delicious Handrawn|h|1",
  "Rubik Pixels|d|1",
  "Gajraj One|d|1",
  "Noto Serif Tangut|r|1",
  "Scoutie Sans|s|15",
  "M PLUS U|s|15",
  "Goblin One|d|1",
  "Grandiflora One|r|1",
  "Noto Sans Runic|s|1",
  "Noto Sans Grantha|s|1",
  "Bona Nova|r|9",
  "Palette Mosaic|d|1",
  "Bubbler One|s|1",
  "Modern Antiqua|d|1",
  "Holtwood One SC|r|1",
  "Noto Serif Dogra|r|1",
  "Medula One|d|1",
  "Noto Sans Old Italic|s|1",
  "Julee|h|1",
  "Meie Script|h|1",
  "Baloo Paaji 2|d|15",
  "Noto Sans Egyptian Hieroglyphs|s|1",
  "Bytesized|s|1",
  "Finlandica Headline|s|15",
  "Poltawski Nowy|r|15",
  "Chokokutai|d|1",
  "Momo Trust Display|s|1",
  "Playpen Sans Thai|h|15",
  "Baumans|d|1",
  "Edu QLD Beginner|h|15",
  "Datatype|m|15",
  "Vampiro One|d|1",
  "Puppies Play|h|1",
  "Edu SA Hand|h|15",
  "Protest Riot|d|1",
  "Noto Sans Old Hungarian|s|1",
  "Noto Sans Tifinagh|s|1",
  "Madimi One|s|1",
  "Noto Serif Gurmukhi|r|15",
  "Hind Mysuru|s|15",
  "Waterfall|h|1",
  "Noto Sans Bamum|s|15",
  "Maiden Orange|r|1",
  "Namdhinggo|r|15",
  "Mako|s|1",
  "Noto Sans Miao|s|1",
  "Baloo Chettan 2|d|15",
  "Noto Sans Khojki|s|1",
  "Sirivennela|s|1",
  "Lily Script One|d|1",
  "Noto Sans Avestan|s|1",
  "Noto Sans Cuneiform|s|1",
  "Noto Serif NP Hmong|r|15",
  "Hanalei|d|1",
  "Mochiy Pop P One|s|1",
  "Monofett|m|1",
  "Noto Sans Tagbanwa|s|1",
  "Rubik Maze|d|1",
  "Shanti|s|1",
  "Noto Sans Syriac Eastern|s|15",
  "Noto Traditional Nushu|s|15",
  "Sumana|r|9",
  "Yuyu Short|h|1",
  "Odibee Sans|d|1",
  "Yuyu|h|1",
  "Uncial Antiqua|d|1",
  "Noto Znamenny Musical Notation|s|1",
  "Alan Sans|s|15",
  "Rubik Storm|d|1",
  "Noto Sans Lydian|s|1",
  "Ribeye|d|1",
  "Noto Sans Cham|s|15",
  "Smooch|h|1",
  "Tuffy|s|9",
  "Bpmf Zihi Kai Std|s|1",
  "Nova Flat|d|1",
  "Bitcount Prop Double Ink|d|15",
  "Victor Mono|m|15",
  "Mingzat|s|1",
  "Iceland|d|1",
  "Noto Sans Lisu|s|15",
  "Crushed|d|1",
  "Noto Sans Nabataean|s|1",
  "BJCree|r|15",
  "Jersey 10|d|1",
  "Noto Serif Makasar|r|1",
  "Blaka Hollow|d|1",
  "Blaka Ink|d|1",
  "Esteban|r|1",
  "Libre Barcode 128 Text|d|1",
  "Noto Sans Palmyrene|s|1",
  "Noto Serif Ottoman Siyaq|r|1",
  "Noto Serif Khitan Small Script|r|1",
  "Yuji Hentaigana Akari|h|1",
  "Noto Sans Elbasan|s|1",
  "Huninn|s|1",
  "Noto Sans Deseret|s|1",
  "Noto Serif Hentaigana|r|15",
  "Noto Sans Mahajani|s|1",
  "Bonheur Royale|h|1",
  "Noto Sans Old Persian|s|1",
  "Kavoon|d|1",
  "Noto Sans Newa|s|1",
  "Noto Sans Zanabazar Square|s|1",
  "Maname|r|1",
  "Bitcount Prop Double|d|15",
  "Noto Sans Siddham|s|1",
  "Ysabeau SC|s|15",
  "Edu VIC WA NT Hand|h|15",
  "Noto Sans NKo Unjoined|s|15",
  "Libertinus Keyboard|d|1",
  "Jacquard 12 Charted|d|1",
  "Noto Sans Tai Tham|s|15",
  "Noto Sans Inscriptional Parthian|s|1",
  "Noto Sans Old North Arabian|s|1",
  "Noto Serif Old Uyghur|r|1",
  "Edu NSW ACT Hand Pre|h|15",
  "Gafata|s|1",
  "Noto Sans SignWriting|s|1",
  "Jersey 10 Charted|d|1",
  "Bitcount Single Ink|d|15",
  "Noto Sans Chakma|s|1",
  "Noto Sans Old South Arabian|s|1",
  "Noto Sans Phoenician|s|1",
  "Stick|s|1",
  "Bitcount Prop Single Ink|d|15",
  "Noto Sans Caucasian Albanian|s|1",
  "Noto Sans Sogdian|s|1",
  "Englebert|s|1",
  "Jacquard 24 Charted|d|1",
  "Betania Patmos In|h|1",
  "Jersey 15 Charted|d|1",
  "IM Fell DW Pica SC|r|1",
  "Noto Sans Linear B|s|1",
  "Edu TAS Beginner|h|15",
  "Overlock SC|d|1",
  "Edu VIC WA NT Hand Pre|h|15",
  "Honk|d|1",
  "Noto Sans Masaram Gondi|s|1",
  "Micro 5 Charted|d|1",
  "Rubik Bubbles|d|1",
  "Noto Sans New Tai Lue|s|15",
  "Liu Jian Mao Cao|h|1",
  "Noto Sans Rejang|s|1",
  "Bitcount Ink|d|15",
  "Bokor|d|1",
  "Noto Sans Tamil Supplement|s|1",
  "Noto Sans Mro|s|1",
  "Baloo Tammudu 2|d|15",
  "Denk One|s|1",
  "Noto Sans Psalter Pahlavi|s|1",
  "Betania Patmos In GDL|h|1",
  "Yomogi|h|1",
  "Noto Sans Tirhuta|s|1",
  "Jersey 25 Charted|d|1",
  "Yuji Hentaigana Akebono|h|1",
  "Kotta One|r|1",
  "Noto Sans Syriac Western|s|15",
  "Anek Kannada|s|15",
  "Noto Sans PhagsPa|s|1",
  "Jersey 20 Charted|d|1",
  "Junge|r|1",
  "Noto Sans Ogham|s|1",
  "Cascadia Code|s|15",
  "Dorsa|s|1",
  "Noto Sans Lepcha|s|1",
  "Noto Sans Old Sogdian|s|1",
  "Jacquarda Bastarda 9 Charted|d|1",
  "Macondo Swash Caps|d|1",
  "Noto Sans Chorasmian|s|1",
  "Noto Sans Manichaean|s|1",
  "Truculenta|s|15",
  "Noto Sans Modi|s|1",
  "Noto Sans Saurashtra|s|1",
  "Delius Unicase|h|9",
  "Mozilla Text|s|15",
  "Genos|s|15",
  "Noto Sans Kayah Li|s|15",
  "IM Fell Double Pica SC|r|1",
  "Jolly Lodger|d|1",
  "Yarndings 12 Charted|d|1",
  "Miniver|d|1",
  "Yarndings 20|d|1",
  "Bodoni Moda SC|r|15",
  "Anek Gujarati|s|15",
  "Moderustic|s|15",
  "Pliant|s|15",
  "Gorditas|d|9",
  "Kenia|d|1",
  "East Sea Dokdo|h|1",
  "IM Fell French Canon SC|r|1",
  "Kulim Park|s|13",
  "Nova Slim|d|1",
  "Kavivanar|h|1",
  "Noto Serif Malayalam|r|15",
  "Hubot Sans|s|15",
  "Caesar Dressing|d|1",
  "Beau Rivage|h|1",
  "Bruno Ace|d|1",
  "Agdasima|s|9",
  "Tiro Devanagari Sanskrit|r|1",
  "Stack Sans Headline|s|15",
  "Cactus Classical Serif|r|1",
  "Astloch|d|9",
  "Mate SC|r|1",
  "Bitcount Grid Double|d|15",
  "Jomolhari|r|1",
  "Port Lligat Slab|r|1",
  "Srisakdi|d|9",
  "Devonshire|h|1",
  "Sekuya|d|1",
  "New Amsterdam|s|1",
  "BBH Bartle|s|1",
  "Ruthie|h|1",
  "Noto Serif Kannada|r|15",
  "Sonsie One|d|1",
  "Nerko One|h|1",
  "Single Day|d|1",
  "Joan|r|1",
  "Smokum|d|1",
  "Gentium Plus|r|9",
  "Cagliostro|s|1",
  "Londrina Shadow|d|1",
  "Comforter|h|1",
  "Cute Font|d|1",
  "Lexend Tera|s|15",
  "Arbutus|r|1",
  "Rum Raisin|s|1",
  "Averia Gruesa Libre|d|1",
  "Chilanka|h|1",
  "Noto Serif Ahom|r|1",
  "Text Me One|s|1",
  "Kaisei HarunoUmi|r|11",
  "Climate Crisis|d|1",
  "Tiro Gurmukhi|r|1",
  "Tac One|s|1",
  "Stack Sans Notch|s|15",
  "Stoke|r|1",
  "Sono|s|15",
  "Braah One|s|1",
  "Flamenco|d|1",
  "Condiment|h|1",
  "Notable|s|1",
  "Paprika|d|1",
  "Bungee Hairline|d|1",
  "Yaldevi|s|15",
  "Nabla|d|1",
  "Texturina|r|15",
  "Lugrasimo|h|1",
  "Noto Serif Lao|r|15",
  "Ramaraja|r|1",
  "Keania One|d|1",
  "Vibes|d|1",
  "Encode Sans SC|s|15",
  "Noto Sans Linear A|s|1",
  "Playpen Sans Arabic|h|15",
  "Rubik Wet Paint|d|1",
  "Winky Sans|s|15",
  "Yuji Boku|r|1",
  "Kumar One|d|1",
  "Shalimar|h|1",
  "Noto Serif Armenian|r|15",
  "Tulpen One|d|1",
  "Monomakh|d|1",
  "Comforter Brush|h|1",
  "Milonga|d|1",
  "Federant|d|1",
  "Libre Barcode EAN13 Text|d|1",
  "Koh Santepheap|r|9",
  "Piedra|d|1",
  "Fruktur|d|1",
  "Alumni Sans Pinstripe|s|1",
  "Noto Sans Vai|s|1",
  "Bitcount Prop Single|d|15",
  "Bungee Tint|d|1",
  "Edu NSW ACT Foundation|h|15",
  "Almendra SC|r|1",
  "Ravi Prakash|d|1",
  "Trykker|r|1",
  "Emblema One|d|1",
  "Fleur De Leah|h|1",
  "Chiron Sung HK|r|15",
  "Noto Sans Mende Kikakui|s|1",
  "Reem Kufi Fun|s|15",
  "Tilt Prism|d|1",
  "Almendra Display|d|1",
  "Dai Banna SIL|r|15",
  "LXGW WenKai Mono TC|m|9",
  "Dr Sugiyama|h|1",
  "My Soul|h|1",
  "Buda|d|1",
  "Metal|d|1",
  "Wellfleet|r|1",
  "Noto Serif Sinhala|r|15",
  "Noto Sans Lao Looped|s|15",
  "Hubballi|s|1",
  "Galdeano|s|1",
  "Noto Sans Nandinagari|s|1",
  "Butcherman|d|1",
  "Bungee Outline|d|1",
  "Noto Serif Gujarati|r|15",
  "Playpen Sans Hebrew|h|15",
  "Stalinist One|d|1",
  "Bigelow Rules|d|1",
  "WDXL Lubrifont SC|s|1",
  "Noto Serif Tibetan|r|15",
  "Chiron Hei HK|s|15",
  "Epunda Sans|s|15",
  "Kirang Haerang|d|1",
  "Noto Sans Anatolian Hieroglyphs|s|1",
  "Noto Sans Glagolitic|s|1",
  "Kedebideri|s|15",
  "TASA Explorer|s|15",
  "GFS Neohellenic|s|9",
  "BBH Hegarty|s|1",
  "Noto Sans Tangsa|s|15",
  "Workbench|m|1",
  "Aubrey|d|1",
  "Twinkle Star|h|1",
  "Cossette Texte|s|9",
  "Tiro Telugu|r|1",
  "Alumni Sans Collegiate One|s|1",
  "Molle|h|1",
  "Lunasima|s|9",
  "Oldenburg|d|1",
  "Flavors|d|1",
  "Iosevka Charon|m|11",
  "Kumar One Outline|d|1",
  "Alien Block|d|1",
  "Gveret Levin|h|1",
  "Noto Sans Marchen|s|1",
  "Mrs Sheppards|h|1",
  "Moulpali|s|1",
  "Tsukimi Rounded|s|15",
  "Zen Loop|d|1",
  "Danfo|r|1",
  "Explora|h|1",
  "Protest Guerrilla|d|1",
  "Noto Sans Multani|s|1",
  "Alumni Sans SC|s|15",
  "Rubik Puddles|d|1",
  "Trochut|d|9",
  "Jacquard 24|d|1",
  "Rubik Gemstones|d|1",
  "Rock 3D|d|1",
  "Noto Sans Batak|s|1",
  "Noto Sans Pau Cin Hau|s|1",
  "Finlandica Text|s|15",
  "Tapestry|h|1",
  "Noto Sans Hanunoo|s|1",
  "Big Shoulders Inline|d|15",
  "WDXL Lubrifont TC|s|1",
  "BBH Bogle|s|1",
  "UoqMunThenKhung|r|1",
  "LXGW Marker Gothic|s|1",
  "Snowburst One|d|1",
  "Tirra|s|15",
  "Petemoss|h|1",
  "Iosevka Charon Mono|m|11",
  "Agu Display|d|1",
  "Noto Sans Mongolian|s|1",
  "Grechen Fuemen|h|1",
  "Caacupe One|d|1",
  "Suravaram|r|1",
  "Noto Sans Indic Siyaq Numbers|s|1",
  "Ponomar|d|1",
  "Libertinus Serif Display|d|1",
  "Ingrid Darling|h|1",
  "Parastoo|r|15",
  "Ruge Boogie|h|1",
  "Winky Rough|s|15",
  "Savate|s|15",
  "Noto Sans Old Turkic|s|1",
  "Rubik Broken Fax|d|1",
  "Asap Sharp|s|15",
  "Noto Sans Syloti Nagri|s|1",
  "Tagesschrift|d|1",
  "Moirai One|d|1",
  "Ole|h|1",
  "M PLUS Code Latin|s|15",
  "Bpmf Huninn|s|1",
  "Bahianita|d|1",
  "Bitcount|d|15",
  "Pochaevsk|d|1",
  "Noto Serif Yezidi|r|15",
  "Geomini|s|15",
  "Miranda Sans|s|15",
  "Playpen Sans Deva|h|15",
  "Noto Serif Toto|r|15",
  "Noto Sans Cypriot|s|1",
  "Exile|d|1",
  "Sankofa Display|s|1",
  "Rubik Doodle Triangles|d|1",
  "Noto Sans Adlam Unjoined|s|15",
  "Lisu Bosa|r|15",
  "Noto Sans Osage|s|1",
  "Noto Sans Duployan|s|9",
  "Rubik Maps|d|1",
  "Hibur Mono|m|1",
  "Edu AU VIC WA NT Pre|h|15",
  "Noto Serif Oriya|r|15",
  "Jaini|d|1",
  "Montenegrin Gothic One|r|1",
  "Noto Serif Todhri|r|1",
  "Shafarik|d|1",
  "Noto Sans Medefaidrin|s|15",
  "Saira Stencil|d|15",
  "Warnes|d|1",
  "Noto Sans Tai Le|s|1",
  "Ponnala|d|1",
  "Jaini Purva|d|1",
  "Rubik Lines|d|1",
  "Noto Sans Meroitic|s|1",
  "Edu QLD Hand|h|15",
  "Edu AU VIC WA NT Arrows|h|15",
  "Noto Sans Brahmi|s|1",
  "Noto Serif Grantha|r|1",
  "Noto Sans Wancho|s|1",
  "Betania Patmos|h|1",
  "Bitcount Grid Single Ink|d|15",
  "Noto Sans Buginese|s|1",
  "Matangi|s|15",
  "Noto Sans Imperial Aramaic|s|1",
  "Bpmf Iansui|h|1",
  "Noto Sans Inscriptional Pahlavi|s|1",
  "Noto Sans Ugaritic|s|1",
  "Kay Pho Du|r|15",
  "Padyakke Expanded One|r|1",
  "Noto Sans Hanifi Rohingya|s|15",
  "Noto Sans Elymaic|s|1",
  "Noto Sans Sharada|s|1",
  "Noto Sans Mayan Numerals|s|1",
  "Noto Sans Hatran|s|1",
  "Noto Sans Kawi|s|15",
  "Bitcount Grid Double Ink|d|15",
  "Strichpunkt Sans|s|15",
  "Yarndings 20 Charted|d|1",
  "Noto Sans Limbu|s|1",
  "Noto Sans Mandaic|s|1",
  "Noto Sans Bassa Vah|s|15",
  "Kanchenjunga|s|15",
  "Betania Patmos GDL|h|1",
  "Noto Sans Soyombo|s|1",
  "Noto Sans Gunjala Gondi|s|15",
  "Noto Sans Khudawadi|s|1",
  "Noto Sans Nushu|s|1",
  "Noto Sans Kharoshthi|s|1",
  "Ramsina|r|1",
  "Yarndings 12|d|1",
];
